"""primeira migrate do banco de dados

Revision ID: d0813ed64933
Revises: 
Create Date: 2025-10-27 22:36:21.571296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0813ed64933'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('nome_contato', sa.String(length=100), nullable=True),
    sa.Column('email_contato', sa.String(length=100), nullable=True),
    sa.Column('telefone_contato', sa.String(length=20), nullable=True),
    sa.Column('cargo_contato', sa.String(length=100), nullable=True),
    sa.Column('departamento_contato', sa.String(length=100), nullable=True),
    sa.Column('celular_contato', sa.String(length=20), nullable=True),
    sa.Column('eh_cliente', sa.Boolean(), nullable=True),
    sa.Column('bus_contratados', sa.String(length=500), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('skype', sa.String(length=100), nullable=True),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('indicacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('bu_indicado', sa.String(length=100), nullable=False),
    sa.Column('produtos_escolhidos', sa.String(length=500), nullable=True),
    sa.Column('quantidade_caminhoes', sa.Integer(), nullable=True),
    sa.Column('quantidade_funcionarios', sa.Integer(), nullable=True),
    sa.Column('quantidade_veiculos_pesados', sa.Integer(), nullable=True),
    sa.Column('subsidia_combustivel', sa.Boolean(), nullable=True),
    sa.Column('quantidade_veiculos_leves', sa.Integer(), nullable=True),
    sa.Column('quantidade_veiculos', sa.Integer(), nullable=True),
    sa.Column('previsao_volume', sa.Float(), nullable=True),
    sa.Column('quantidade_cartoes', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_indicacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicacao')
    op.drop_table('usuario')
    op.drop_table('empresa')
    # ### end Alembic commands ###
